theme: minima
title: Why you should care about global warming ... and what you can do!
author: Raoul
email: r.teeuwen@pure-energie.nl
description: > # this means to ignore newlines until "baseurl:"
  About global warming, why people should care, and 
  what they can actually do themselves

# social links
twitter_username: raoulteeuwen
github_username:  raoulteeuwenPE

show_excerpts: true # set to false to remove excerpts on the homepage
